global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: 'github_exporter'
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'localhost:9171'
