version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9000:9090"
    volumes:
      - /home/pi/IT-Tec_Prometheus/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/home/pi/IT-Tec_Prometheus/prometheus/prometheus.yml
  github-exporter:
    image: infinitywork/github-exporter:latest
    ports:
      - "9171:9171"
    expose:
      - 9171
    tty: true
    stdin_open: true
    environment:
      - ORGS="KlaraOppenheimerSchule"

volumes:
  prometheus-data:
