version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9000:9090"
    volumes:
      - ../prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  github-exporter:
    image: github-exporter-arm64
    ports:
      - "9171:9171"
    expose:
      - 9171
    tty: true
    stdin_open: true
    environment:
      - ORGS=KlaraOppenheimerSchule

volumes:
  prometheus-data:
